### PR TITLE
fix: encode the csv data before save

### PR DESCRIPTION
**Pull request by arslanashraf7**
**Description:** Describe in a couple of sentences what this PR adds
This PR adds python's default(`utf-8`) encoding on the file data before saving.
This is not needed in the case of local storage while manipulating the grades but it becomes an issue when we use AWS/S3 storage as a backend instead of the local storage. The s3 services throw errors about file encoding.

A sample error log is attached below.

**JIRA:** Link to JIRA ticket
More details can be seen on https://github.com/mitodl/mitxonline/issues/415

**Dependencies:** dependencies on other outstanding PRs, issues, etc. 
None

**Merge deadline:** List merge deadline (if any)
No Specific Date but Soon

**Installation instructions:** List any non-trivial installation 
instructions.
- Just set up the S3 backend storage for grades and then follow the instructions in https://github.com/mitodl/mitxonline/issues/415 to reproduce and verify the fix.

**Testing instructions:**
Mentioned in https://github.com/mitodl/mitxonline/issues/415

**Sample Error Log**
The sample error log can be seen:
```
2022-04-11 21:05:44,654 ERROR 7292 [root] [user None] [ip None] signals.py:22 - Uncaught exception from None
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/bulk_grades/views.py", line 45, in dispatch
    return super().dispatch(request, course_id, *args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/bulk_grades/views.py", line 98, in post
    self.processor.process_file(the_file, autocommit=True)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/super_csv/csv_processor.py", line 188, in process_file
    self.preprocess_file(reader)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/bulk_grades/api.py", line 355, in preprocess_file
    self.save()
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/bulk_grades/api.py", line 333, in save
    return super().save(operating_user=self._user)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/super_csv/mixins.py", line 118, in save
    operation = CSVOperation.record_operation(
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/super_csv/models.py", line 72, in record_operation
    instance.data.save(uuid.uuid4(), ContentFile(data))
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/db/models/fields/files.py", line 89, in save
    self.name = self.storage.save(name, content, max_length=self.field.max_length)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/core/files/storage.py", line 54, in save
    name = self._save(name, content)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/storages/backends/s3boto3.py", line 495, in _save
    self._save_content(obj, content, parameters=parameters)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/storages/backends/s3boto3.py", line 510, in _save_content
    obj.upload_fileobj(content, ExtraArgs=put_parameters)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/boto3/s3/inject.py", line 511, in object_upload_fileobj
    return self.meta.client.upload_fileobj(
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/boto3/s3/inject.py", line 431, in upload_fileobj
    return future.result()
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/s3transfer/futures.py", line 73, in result
    return self._coordinator.result()
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/s3transfer/futures.py", line 233, in result
    raise self._exception
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/s3transfer/tasks.py", line 126, in __call__
    return self._execute_main(kwargs)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/s3transfer/tasks.py", line 150, in _execute_main
    return_value = self._main(**kwargs)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/s3transfer/upload.py", line 692, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/botocore/client.py", line 317, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/botocore/client.py", line 591, in _make_api_call
    handler, event_response = self.meta.events.emit_until_response(
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/botocore/hooks.py", line 242, in emit_until_response
    responses = self._emit(event_name, kwargs, stop_on_response=True)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/botocore/handlers.py", line 209, in conditionally_calculate_md5
    calculate_md5(params, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/botocore/handlers.py", line 187, in calculate_md5
    binary_md5 = _calculate_md5_from_file(body)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/botocore/handlers.py", line 201, in _calculate_md5_from_file
    md5.update(chunk)
TypeError: Unicode-objects must be encoded before hashing

```
**Reviewers:**
- [ ] tag reviewer 
- [ ] tag reviewer 

**Merge checklist:**
- [x] All reviewers approved
- [x] CI build is green
- [x] Version bumped
- [x] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [x] Create a tag
- [x] Check new version is pushed to PyPI after tag-triggered build is 
      finished.
- [x] Delete working branch (if not needed anymore)

**Author concerns:** List any concerns about this PR - inelegant 
solutions, hacks, quick-and-dirty implementations, concerns about 
migrations, etc.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @arslanashraf7! I've created [OSPR-6612](https://openedx.atlassian.net/browse/OSPR-6612) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@arslanashraf7 Thank you for your contribution. Is this ready for our review?

**Comment by arslanashraf7** [comment]
@natabene Yes, it's ready for review.

**Comment by openedx-webhooks** [comment]
@arslanashraf7 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/super-csv&entry.867055334=https://github.com/openedx/super-csv/pull/100&entry.1484655318=https://github.com/arslanashraf7&entry.752974735=2022-04-13+10:10&entry.1917517419=2022-08-15+14:44&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
