### PR TITLE
Fix syntax warning over comparison of literals using is.

### LINKED ISSUE #26: Syntax warning due to comparison of literals using is
* super-csv version: master branch
* Python version: 3.8
* Operating System: Linux

### Description

```
find . -iname '*py' | grep -Ev 'setup|rdf4|tool' | xargs -P4 -I{} python3.8 -Wall -m py_compile {}
./tests/test_models.py:25: SyntaxWarning: "is" with a literal. Did you mean "=="?
  assert operation.data.name is ''
```

### PR DESCRIPTION
**Pull request by tirkarthi**
**Description:** Fixes syntax warnings. Closes #26 

**Reviewers:**
- [ ] tag reviewer 
- [ ] tag reviewer 

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPI after tag-triggered build is 
      finished.
- [ ] Delete working branch (if not needed anymore)

**Author concerns:** List any concerns about this PR - inelegant 
solutions, hacks, quick-and-dirty implementations, concerns about 
migrations, etc.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @tirkarthi! I've created [OSPR-4406](https://openedx.atlassian.net/browse/OSPR-4406) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://open.edx.org/wp-content/uploads/2019/01/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by natabene** [comment]
@tirkarthi Thank you for the contribution! When you have a chance, could you please send in a signed Contributor Agreement mentioned in the earlier comment? You only need to do this once and we can then review all your future code contributions. Thanks

**Comment by tirkarthi** [comment]
Sorry, I might not be able to go ahead due to CLA. Since the fix is simple enough I will leave it to someone who can move it forward with the patch.

**Comment by edx-webhook** [comment]
@tirkarthi Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/super-csv&entry.867055334=https://github.com/edx/super-csv/pull/27&entry.1484655318=https://github.com/tirkarthi&entry.752974735=2020-04-21+14:18&entry.1917517419=2020-04-22+14:30&entry.2133058324=No) so we can improve your experience in the future.

**Comment by natabene** [comment]
@tirkarthi Sorry to hear, is there any way I can help you with the CLA? Are you missing necessary equipment or do the rights for this change not belong to you?

**Pull request closed without merging**
